# Creates all 1 store types using kfutil.
# kfutil reads definitions from the Keyfactor integration catalog.
#
# Auth environment variables (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_HOSTNAME + KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD
#                         + KEYFACTOR_DOMAIN
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

# Uncomment if kfutil is not in your PATH
# Set-Alias -Name kfutil -Value 'C:\Program Files\Keyfactor\kfutil\kfutil.exe'

if ($null -eq (Get-Command "kfutil" -ErrorAction SilentlyContinue)) {
    Write-Host "kfutil could not be found. Please install kfutil"
    Write-Host "See https://github.com/Keyfactor/kfutil#quickstart"
    exit 1
}

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Host "KEYFACTOR_HOSTNAME not set — launching kfutil login"
    & kfutil login
}

& kfutil store-types create --name "PaloAlto"

Write-Host "Done. All store types created."
