# Creates all 1 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# PaloAlto — Either the Panorama or Palo Alto Firewall URI or IP address.
# ---------------------------------------------------------------------------
New-StoreType "PaloAlto" @'
{
  "Name": "PaloAlto",
  "ShortName": "PaloAlto",
  "Capability": "PaloAlto",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DeviceGroup",
      "DisplayName": "Device Group",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "InventoryTrustedCerts",
      "DisplayName": "Inventory Trusted Certs",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "TemplateStack",
      "DisplayName": "Template Stack",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "PushFailureBehavior",
      "DisplayName": "Push Failure Behavior",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "Failure,Warning",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The Store Path field should be reviewed in the store path explanation section.  It varies depending on configuration.",
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@


Write-Host "Completed."
