run-name: Build and Test Solution - ${{ github.sha }}
name: Build and Test Solution

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build-and-test-solution:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            dotnet-version: [ '6.0.x', '8.0.x' ]
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup .NET 6
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '6.0.x'

        - name: Setup .NET 8
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Add Keyfactor NuGet Source
          run: dotnet nuget add source https://nuget.pkg.github.com/Keyfactor/index.json -n github -u ${{ github.actor }} -p ${{ secrets.V2BUILDTOKEN }} --store-password-in-clear-text
        
        - name: Restore Dependencies
          run: dotnet restore

        - name: Build solution
          run: dotnet build --no-restore --configuration Release

        - name: Run Unit Tests
          run: dotnet test --configuration Release --no-build --filter "Category!=Integration"