#!/usr/bin/env bash

# Creates all 1 store types using kfutil.
# kfutil reads definitions from the Keyfactor integration catalog.
#
# Auth environment variables (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_HOSTNAME + KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD
#                         + KEYFACTOR_DOMAIN
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if ! command -v kfutil &> /dev/null; then
    echo "kfutil could not be found. Please install kfutil"
    echo "See https://github.com/Keyfactor/kfutil#quickstart"
    exit 1
fi

if [ -z "$KEYFACTOR_HOSTNAME" ]; then
    echo "KEYFACTOR_HOSTNAME not set — launching kfutil login"
    kfutil login
fi

kfutil store-types create --name "PaloAlto"

echo "Done. All store types created."
